export const hotels = [
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: 'Danubius Hotel Regents Park',
    price: '$200 Par Night',
    rating: 4.8,
    popular: true,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: 'The Resident Soho',
    price: '$250 Par Night',
    rating: 4.7,
    popular: true,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: 'London Bridge Hotel',
    price: '$200 Par Night',
    rating: 4.8,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: '3 The Resident Soho',
    price: '$150 Par Night',
    rating: 4.7,
    popular: true,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: '4 London Bridge Hotel',
    price: '$100 Par Night',
    rating: 3.8,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: '5 The Resident Soho',
    price: '$280 Par Night',
    rating: 4.7,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: 'London Bridge Hotel',
    price: '$200 Par Night',
    rating: 3.8,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: 'The Resident Soho',
    price: '$220 Par Night',
    rating: 4.7,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: 'London Bridge Hotel',
    price: '$260 Par Night',
    rating: 3.8,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: 'The Resident Soho',
    price: '$200 Par Night',
    rating: 4.7,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    address: 'London NW8 7JT England',
    title: 'London Bridge Hotel',
    price: '$200 Par Night',
    rating: 3.8,
  },
]