export const hotels = [
  {
    img: './public/assets/images/avatar-1.webp',
    subtitle: 'Hotel 1',
    title: 'Danubius Hotel Regents Park',
    price: 150,
    rating: 4.5,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 2',
    title: 'The Resident Soho',
    price: 120,
    rating: 4.7,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 3',
    title: 'London Bridge Hotel',
    price: 100,
    rating: 3.8,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 2',
    title: 'The Resident Soho',
    price: 120,
    rating: 4.7,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 3',
    title: 'London Bridge Hotel',
    price: 100,
    rating: 3.8,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 2',
    title: 'The Resident Soho',
    price: 120,
    rating: 4.7,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 3',
    title: 'London Bridge Hotel',
    price: 100,
    rating: 3.8,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 2',
    title: 'The Resident Soho',
    price: 120,
    rating: 4.7,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 3',
    title: 'London Bridge Hotel',
    price: 100,
    rating: 3.8,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 2',
    title: 'The Resident Soho',
    price: 120,
    rating: 4.7,
  },
  {
    img: 'https://i.tez-tour.travel/img/hotels/112768/0.jpg',
    subtitle: 'Hotel 3',
    title: 'London Bridge Hotel',
    price: 100,
    rating: 3.8,
  },
]